site_name: Avantis wet en regelgeving
site_url: https://example.com
site_description: 'Wet en regelgeving van Avantis roleplay'
site_author: 'xRadeCoding'

copyright: AvantisRP • © alle rechten voorbehouden | 2021 - 2022

theme:
  name: material
#   features:
#     - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  favicon: https://i.imgur.com/2AREa4C.png
  logo: https://i.imgur.com/2AREa4C.png
  custom_dir: docs/overrides
  language: nl
  extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
  - Wetboek: wetboek.md
  - Risicogebieden: risico-gebieden.md
  - Belastingen: belastingen.md
  - Offroad Voertuigen: offroadvoertuigen.md
  - NOTAM: notam.md
  - Tarief:
    - Ambulance: Tarief/ambulance.md
    - ANWB: Tarief/anwb.md
    - Politie: Tarief/politie.md
    - Vliegschool: Tarief/vliegschool.md